### ISSUE TITLE
Callback- & Error-related tests are failing

### ISSUE THREAD

**Issue by tomalec** [Palindrom/Palindrom#103]
It seems they were not updated to match features implemented recently.

@joozek78 Could you take it, as you created new flow and you know what should be tested

PS, Please note, that all the other tests are passing, so hope fully after this one PuppetJS will be all green, at least in Chrome

**Comment by warpech** [comment]
@tomalec was this fixed?

**Comment by joozek78** [comment]
@warpech not yet

**Comment by warpech** [comment]
In beb6012 @tomalec has disabled the failing tests. @joozek78 pls take action to fix the tests. Thanks

**Comment by warpech** [comment]
I will merge beb6012 to `gh-pages` when I get the PR from @tomalec

**Comment by alshakero** [comment]
@joozek78 if by any chance you were to implement these, I'd like to inform you not to. I'm re-writing the tests with Mocha and came across this. Will write them anyways.

**Comment by alshakero** [comment]
Closing as solved in https://github.com/Palindrom/Palindrom/pull/130.
