### ISSUE TITLE
Migrate tests to mocha + WCT, or separate puppet-dom

### ISSUE THREAD

**Issue by tomalec** [Palindrom/Palindrom#104]
puppet-dom tests requires Shadow DOM polyfill - what makes it impossible to run from commandline => to setup Travis w/o Selenium (https://github.com/PuppetJs/PuppetJs/issues/89).

Therefore I'd suggest to test puppet-dom wit WCT. The question is whether we should:
1. Migrate all even non-DOM related tests to Web Components Tester,
2. Separate the puppet-dom to own repo.

(there is also a point that jasmine command line reporter is buggy)
//cc @warpech

**Comment by warpech** [comment]
Why exactly does it require Shadow DOM polyfill?

**Comment by tomalec** [comment]
It creates Nodes in Shadow DOM
https://github.com/PuppetJs/PuppetJs/blob/gh-pages/test/spec/dom/LinksSpec.js#L47

**Comment by warpech** [comment]
Maybe:

3 . Move that one test to puppet-polymer-client, which already is tested using WCT?

**Comment by tomalec** [comment]
I don't like 3. as this is not just one test, but 4 tests for functionality clearly coded at https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet-dom.js

So, I would rather agree on moving puppet-dom stuff to `<p-p-c>`. However, as it is Polymer, and Custom Element independent stuff I'd prefer 2.

**Comment by warpech** [comment]
I have noticed that some polyfills (dmarcos) test in Node using phantomjs: https://github.com/dmarcos/document-register-element/blob/master/package.json

Maybe we should do that as well instead of using jsdom?

**Comment by tomalec** [comment]
I have added sketchy integration it with PhantomJS at https://github.com/PuppetJs/PuppetJs/compare/phantomjs?expand=1
So it runs in CLI and shows that we have failing tests for polyfilled browsers.

It still requires implementing full console reporter, hacking the lack of support for `console.*` (other than `.log`) in Phantom, checking if polyfills are applied correctly etc.

After experiencing all that pain with Phantom, Jasmine, jsdom, etc for couple of weeks I would really vote for stronger separation of DOM related stuff, and:

1. Run `puppet.js` related tests in CLI with jasmine only - as it should work fluently w/o browser.
 - run it against `puppet.js` 
 - run it against `puppet.js` + `puppet-dom.js` - as `-dom` should not break puppets features
2. Rewrite `puppet-dom.js` related tests (28 specs) to mocha,
3. Run `puppet-dom.js` related tests with Selenium on all the browsers (WCT + SauceLabs) - as dom features should work in browser and in all browsers.
4. Maybe later on we could separate `-dom` features to `puppet-client`

I think the plan above, gives us best coverage, and could be implemented step by step.
For the sake of this issue, https://github.com/PuppetJs/PuppetJs/issues/105 , and the need of having automated and green tests, we could do just 1.

The other may wait for a person dedicated to test automation, or just someone who will have time to do so.

@warpech WDYT?

**Comment by warpech** [comment]
cc @alshakero

**Comment by alshakero** [comment]
This is long closable right?

**Comment by warpech** [comment]
I think so, in my "cc @alshakero" I counted on you picking up the relation between this issue and https://github.com/Palindrom/Palindrom/pull/130.

So where are we? The purpose of this issue expressed in the OP was to enable testing Palindrom in CLI without Selenium. 

Currently tests are migrated to Mocha, but what about PalindromDom and WCT?

**Comment by alshakero** [comment]
Does WCT run in CLI without Selenium? 😮

**Comment by warpech** [comment]
Not really, WCT uses Selenium.

I thought that only PalindromDOM really needs WCT and Selenium. Palindrom itself should be testable in Node without a browser and Selenium.

**Comment by alshakero** [comment]
>  Palindrom itself should be testable in Node without a browser and Selenium.

It is 100% testable
```sh
npm run test
```
runs perfectly. 

If you want to test the whole thing you can use:

```sh
npm run test-sauce
```

**Comment by warpech** [comment]
Can you pls add the above to https://github.com/Palindrom/Palindrom/blob/master/docs/06-Development.md?

**Comment by alshakero** [comment]
Done: https://github.com/Palindrom/Palindrom/blob/master/docs/06-Development.md

**Comment by warpech** [comment]
Great, thanks! Closing.
