### ISSUE TITLE
Configure Travis CI

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#105]
After #103 is done, configure tests to run in Travis CI

**Comment by tomalec** [comment]
I have marked failing tests from #103 as pending, configured travis.yml, package,json, but I'm still blocked at lack of support for Shadow DOM in jsdom - https://github.com/tmpvar/jsdom/issues/1030- (even with webcomponents.js polyfill loaded) - jsdom does not provide classes like `HTMLElement`, etc. 

I'm afraid we will have to fallback to WCT, and do  https://github.com/PuppetJs/PuppetJs/issues/104 first

**Comment by tomalec** [comment]
Done as part of https://github.com/Palindrom/Palindrom/pull/130

**Comment by alshakero** [comment]
@tomalec this is a beautiful close 🎊
