### ISSUE TITLE
Mock WebSocket in tests with Chaos

### ISSUE THREAD

**Issue by tomalec** [Palindrom/Palindrom#114]
Finally I've found a library that could mock web sockets, I think we should give it a try, instead of implementing it by ourselves.

https://github.com/zzarcon/chaosocket

**Comment by alshakero** [comment]
Doesn't work on Node https://github.com/zzarcon/chaosocket/blob/master/src/fakesocket.js#L7

**Comment by tomalec** [comment]
Seems easy to mock/workaround/fix.

**Comment by alshakero** [comment]
Closing as fixed using [thoov/mock-socket](https://github.com/thoov/mock-socket).
