### ISSUE TITLE
Make demos work again, update test automation

### ISSUE THREAD

**Issue by tomalec** [Palindrom/Palindrom#115]
Currently they do not work due to `Object.observe` and `dom-bind-notifier` issues

I think we should:
- Update Jasmine and jasmine-ajax
- Update our mock server
- Use WebSocket mocks https://github.com/PuppetJs/PuppetJs/issues/114
- In Polymer samples replace `dom-bind-notifier` with `addEventListener('patch-applied')` that does a subset of notifications from https://github.com/PuppetJs/puppet-polymer-client/blob/gh-pages/puppet-client.html#L421

**Comment by alshakero** [comment]
This is done right?

**Comment by tomalec** [comment]
What about 
- angularjs
- polymer_fancy_binding
- polymer_ot
?

**Comment by alshakero** [comment]
Are we really going to waste our time on Angularjs? Angular 2 is dying and they released 4 already. 

I think React and Vue are better investments.

**Comment by tomalec** [comment]
fair point. Speaking of polymer maybe it's better to wait for 2.0 to test border cases and fancy bindings.

Then I'd remove Angular demo completely, add some message at demo pages or create an issue for polymer_fancy_binding & polymer_ot that we will renew it with 2.0

**Comment by alshakero** [comment]
http://palindrom.github.io/Palindrom/lab/index.html

**Comment by warpech** [comment]
https://palindrom.github.io/#/
https://palindrom.github.io/lab/polymer/index.html
https://palindrom.github.io/lab/react/index.html
https://palindrom.github.io/lab/vue/index.html

I think this can be closed. Are the other demos used? Perhaps remove them?

**Comment by alshakero** [comment]
I thought so. But maybe polymer_ot and fancy binding are important? I prefer removing them, but I don't funny understand them.

**Comment by tomalec** [comment]
https://palindrom.github.io/lab/polymer/index.html does not work in Firefox.

> maybe polymer_ot 

I think it would be nice to show case that we can solve conflicts to get eventual consistency. But it comes with the nice demo of OT itself, which I would really like to have some day.

**Comment by warpech** [comment]
Reality shows that so many demos are unmaintainable. Is eventual consistency covered in tests?

**Comment by alshakero** [comment]
@warpech not really. I guess we'll need to simulate network by shuffling patches and sending them to Palindrom and expect it to digest it in the original order. I'll look into it.

**Comment by warpech** [comment]
Frozen until we decide about https://github.com/Palindrom/Palindrom/issues/205

**Comment by warpech** [comment]
Closing as it was decided in https://github.com/Palindrom/Palindrom/issues/205 that the demos should be removed.

Removing of the demos (labs) is tracked in https://github.com/Palindrom/Palindrom/issues/205
