### ISSUE TITLE
Change default setting for remoteUrl/remote-url

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#117]
Current default is that PuppetJs takes `window.location` URL as the JSON URL if `remoteUrl`/`remote-url` is not provided.

This brings unwanted consequences as presented here: https://github.com/Starcounter/Starcounter/issues/4045

Requiring `remoteUrl`/`remote-url` explicitly would prevent such problems and remove some magic.

@miyconst, @tomalec, @Mackiovello WDYT?

**Comment by miyconst** [comment]
+1 from me.

**Comment by alshakero** [comment]
+1 especially we are supporting Node soon.

**Comment by warpech** [comment]
> especially we are supporting Node soon.

Exactly, since there is no `window.location`. So the Node version should just not have `window.location` as the default.

**Comment by tomalec** [comment]
+1

**Comment by warpech** [comment]
Great! @alshakero assigning this to you, I guess it will be solved automatically by switching to the Node version.

**Comment by alshakero** [comment]
@warpech yes, a long time ago.

https://github.com/alshakero/puppet-node/blob/master/src/Puppet.ts#L82

**Comment by tomalec** [comment]
@miyconst, @warpech do you think we can push it to 2.3 and demand apps to adjust? if so @alshakero  could join it with Palindrom renaming at 3.0.0

**Comment by alshakero** [comment]
@tomalec sure, I think we should at least warn about it in Palindrom 3.0.0.

**Comment by tomalec** [comment]
Definitely warning is a good idea. However, unless Marcin or Konstantin will have something against by the end of day today, I would go with pushing it to 3.0.0. So, we would require `remoteUrl` and throw an error if it was not given.

**Comment by warpech** [comment]
I think that we can totally require `remoteUrl` and throw an error if it was not given.

Adapting to it is easy for our users, because it fails instantly.

**Comment by alshakero** [comment]
@warpech and they can simply pass `window.location.href` if they need.

**Comment by warpech** [comment]
Exactly.

**Comment by warpech** [comment]
This can be closed when the changes in README.md are finished. See the comments in https://github.com/Palindrom/Palindrom/commit/61ef7ef28aa369f280c154e476ac615e15b7049e

**Comment by alshakero** [comment]
Done and now is [in README ](https://github.com/Palindrom/Palindrom#options-palindrom-constructor-parameters). Closable right?

**Comment by tomalec** [comment]
:+1: from me

**Comment by warpech** [comment]
Closing as done
