### ISSUE TITLE
Rename to Palindrom

### ISSUE THREAD

**Issue by tomalec** [Palindrom/Palindrom#118]
As we finally decided on the new name here https://github.com/PuppetJs/PuppetJs/issues/83
Now, it's the time to proceed with it.

Here is what I propose:
1. [x] 1. Rename the organization to Palindrom
2. [x] 2. Create a branch in this repo that renames puppet in the code @alshakero Could you take care of it?
    - Add a new logo if we will agree on it by that time :)
3. [x] 3. Release last (patch) version of PuppetJs
4. [x] 4. Merge PR with new name, rename this repo
5. [x] 5. Release last (patch version) of all https://github.com/PuppetJs elements/package that has puppet in name
6. [x] 6. Rename with "palindrom"
7. [x] 7. Update all other references to "puppet" in https://github.com/PuppetJs  and JSON-Patch docs,, articles, wikis
8. [x] 8. Update https://github.com/Starcounter/Docs
9. [x] 9. Create a blog post about it

@warpech @aloscha any comments? If none I will proceed with 1. by the end of today.

**Comment by alshakero** [comment]
> Create a branch in this repo that renames puppet in the code @alshakero Could you take care of it?
Add a new logo if we will agree on it by that time :)

Sure, should I rename all the refs in the same current code? What about the [ported Node version](https://github.com/alshakero/Palindrom)?

**Comment by tomalec** [comment]
> Sure, should I rename all the refs in the same current code? What about the ported Node version?

Yes, in this codebase.
I would Node-ify it also in this repo, after the renaming

**Comment by alshakero** [comment]
@tomalec great. On it.

**Comment by alshakero** [comment]
[One is done](https://github.com/PuppetJs/PuppetJs/tree/rename-to-palindrom). All specs pass, and no regression in `lab` folder errors.

**Comment by alshakero** [comment]
@tomalec will Palindrom 3.0.0 use proxies?

**Comment by alshakero** [comment]
Closing as all done.
