### ISSUE TITLE
Breaking changes and deprecations in Palindrom 3.0.0

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#128]
A new major number (3.0.0) gives us a chance to deprecate or remove already deprecated APIs.

The breaking changes that we have we already made:

1. `remoteUrl` is now required as the input parameter (https://github.com/Palindrom/Palindrom/issues/117)
2. `ignoreAdd` (https://github.com/Palindrom/Palindrom/issues/35, https://github.com/Palindrom/Palindrom/issues/82) - removed in Palindrom 3.0.0

Anything else?

**Comment by alshakero** [comment]
`puppet-redirect-url` event will be deprecated too.

**Comment by warpech** [comment]
@malx122 are you still using `ignoreAdd` big time in your projects?

**Comment by tomalec** [comment]
Flow was changed thanks to proxification, so now we will send patch after each change, no more unpredictable batching. (some users might rely on that glitch)

**Comment by alshakero** [comment]
@tomalec one thing I'm worried about is looping now. When you do this:

```js
for(i = 0; i < 100; i++){
    palindromObj.arr[i] = 1;
}
```
a patch will be sent to the server with every loop in a blocking manner.

**Comment by tomalec** [comment]
Should we introduce transactions to Palindrom :godmode: ?

**Comment by tomalec** [comment]
https://github.com/Palindrom/Palindrom/issues/29

**Comment by alshakero** [comment]
@tomalec I think all we need is two callbacks `beginTransaction` and `endTransaction`. Fairly easy to implement in JSONPatcherProxy.

**Comment by tomalec** [comment]
what about rollback?
I thought about something closer to what we have on server-side:
```js
var node = root.some.path.deeper;
palindrom.batch/transaction(function(root){
    for(i = 0; i < 100; i++){
        node.arr[i] = 1;
    }
});
```

**Comment by alshakero** [comment]
@tomalec sorrry, I deleted my comment to move it there.

**Comment by alshakero** [comment]
@tomalec your solution is perfect IMO.

**Comment by miyconst** [comment]
>@tomalec one thing I'm worried about is looping now. When you do this:

@alshakero although your solution might bring a performance problem by sending many patches with small changes, I don't think we should focus on it now.

If an app has client side logic, in this case loop through array of data and do something, then it is poorly designed.

Such actions should be performed on server side. And client should trigger the action only.

---

It is nice to have transactions in Palindrom, but I would not consider it as a must have and would not even include it in the first release.

**Comment by alshakero** [comment]
> and would not even include it in the first release.

100% agree. I think it's better to release as smoothly as possible with the least potential of introducing bugs. And then maybe enhance.

**Comment by warpech** [comment]
I agree with @miyconst. Only testing will show if  https://github.com/Palindrom/Palindrom/issues/128#issuecomment-291535681 is really a problem, or just a quirk. Anyway, it is very good to mention this in the release notes.

**Comment by warpech** [comment]
All the above points are now in release notes of https://github.com/Palindrom/Palindrom/releases/tag/v3.0.0

Archiving
