### ISSUE TITLE
README notes after proxification

### ISSUE THREAD

**Issue by tomalec** [Palindrom/Palindrom#131]
There is still a section in readme [Generating patches based on local changes](https://github.com/Palindrom/Palindrom#generating-patches-based-on-local-changes) which describes event trick not needed any longer.

**Comment by alshakero** [comment]
@tomalec should I push this change to the same PR? or wait for merging? I think I should do in the same since I modified README already.

**Comment by tomalec** [comment]
I'd say to add it in the same PR when you added Proxies

**Comment by alshakero** [comment]
This is done. Can I close?
