### ISSUE TITLE
Edge tests on SauceLabs

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#132]
TL;DR: Upvote this idea: https://saucelabs.ideas.aha.io/ideas/SLIDEA-I-302

Apparently, Edge fails to parse `webcomponents.js` file on Edge on a certain version of Windows 10. Updating the OS fixes the issue. Unfortunately, SauceLabs uses that very version of Windows 10. I contacted them last week asking for an update and they responded now. I created this issue to post updates here for archiving and indexing purposes.

My email:

> On your VM's version of Windows 10, Edge fails to parse `webcomponents.js` and throws an error. People have investigated and solved the issue by updating Windows 10. So could you please update Windows 10 on your VMs?
> 
> All you need is here: https://github.com/webcomponents/webcomponentsjs/issues/575
> 
> Bonus failed build because of it: https://saucelabs.com/beta/tests/06763186dff14d82a53b55e618a0a670/commands
> 
> Thanks in advance :)

Their today's response:

> Hi Omar,
> 
> I have confirmed with my Dev team that we only provide fresh images without the additional Windows updates. If you would like our VMs to include the latest daily Windows updates, it is best to submit a feature request via our Customer Idea Portal, where our Product team directly reviews input from our customer and prioritizes what will be implemented next based on demand: https://saucelabs.ideas.aha.io/
> 
> We do have plans to provide the Windows 10 Creator Update that may possibly include the Windows update that fixes the issue mentioned on GitHub. We do not have an ETA at the moment, but we will make an announcement once it becomes available on Sauce. Thanks for your patience and understanding.
> 
> Thanks,
> Albert

**Comment by warpech** [comment]
Upvoted.

Do you have any idea what is the EdgeHTML version in their current images? I have just updated to Windows 10 Creator Update on my system.

**Comment by alshakero** [comment]
@warpech Here is  a screen shot from SauceLabs machine 
![image](https://cloud.githubusercontent.com/assets/17054134/25493603/1196cab6-2b77-11e7-89b8-32b25f12712d.png)

And I don't think there is a need tbh.

**Comment by alshakero** [comment]
Sauce finally updated their machines and now Web Components work and our tests are passing. However , they have another new issue and I reported it. They're usually super responsive. 

Here:

> When you start a Sauce-connect tunnel, Chrome and Firefox succeed to access 127.0.0.1 without any issues. However, MS Edge doesn't, and acts like no tunnel is up and running.
> 
> This applies for automated and manual tests. 
> 
> Links:
> Successful Chrome test:
> https://saucelabs.com/beta/tests/74f26a9c0ce94a2d93713bdc2dd82e85
> 
> Failed Edge test on exactly the same setup (tunnel and URL):
> https://saucelabs.com/beta/tests/143553346e304b16b213483b0716c06e
> 
> To reproduce:
> 1- Start a tunnel on your machine.
> 2- Serve HTTP on your machine.
> 3- Start a manual test and access the URL you served.
> 4- Chrome will work, Edge will fail.
> 
> Potentially helpful information:
> 
> In Edge, you set proxy settings to use "http://127.0.0.1:19876/pac.js" config script,  which seems inaccessible. Weirdly, manually removing this from the settings fixes the issue and tunnel would start to work!

**Comment by alshakero** [comment]
They responded with a working solution 💃

**Comment by alshakero** [comment]
Closing as fixed in https://github.com/Palindrom/Palindrom/pull/143

**Comment by warpech** [comment]
:O

**Comment by alshakero** [comment]
IKR! It would never cross my mind. If you're curious they give me [this link](Palindrom) for more info.
