### ISSUE TITLE
Removed objects continue to emit patches when modified 

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#134]
Moving to proxies turns out to has much more to it.

Consider:

```js
var child = { age: 25 };
var parent = { child };

var parentProxy = recursivelyProxifyObject(parent);

var childProxy = parentProxy.child;

jsonpatch.apply(parentProxy, { op: 'remove', path: '/child' });

```
And now:
```js
now parentProxy === {}
```
But `childProxy` is still proxified, and modifying it sends patches to the server. 

There are two solutions (I implemented the first already because I thought there wasn't any others):

1. Modify `JSONPatcherProxy` to use [`Proxy.revokable`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/revocable) and keep track of all the proxified objects in the tree to be able to use `.revoke()` on them later. And to expose `JSONPatcherProxy#revokeProxy(proxy)` to the API. I implemented this already. But it introduces a breaking change; accessing `childProxy` will now throw an error (`Cannot perform 'set'/'get' on a proxy that has been revoked`).

2. Keep the object proxified, but disable all the traps, and this will have backwards compatibility, but I don't really lean to it because: 
    * It keeps deleted objects in memory forever. 
    * It affects performance a little because the object remains uselessly proxifed. And proxies slow performance silently. Palindrom users will detach sub-objects from `obj` tree without any knowledge that they're still proxified and pay performance-wise for it. I'd say throwing an error is more semantic. After all `palindrom.obj` (and its children) are ours, and people should not use it to store data that is deleted from the server side.

Which way should we go?

**Comment by warpech** [comment]
My favourite answer would be (3): leave it up to GC.

> `childProxy` is still proxified, and modifying it sends patches to the server.

How could anyone modify `childProxy` after it was removed from `parentProxy`? 

The operation that created the patch `jsonpatch.apply(parentProxy, { op: 'remove', path: '/child' });` should simultaneously remove the Polymer bindings to the `child`, so `childProxy` should become GC-able.

Could you pls create a demo page for the problem?

**Comment by alshakero** [comment]
@warpech Can you look at this spec? It illustrates the issue quite clearly. It doesn't pass with Proxies.

https://github.com/Palindrom/palindrom-polymer-client/blob/master/test/d-b-n_smoke/arrays.html#L355

**Comment by warpech** [comment]
It appears that `revocable` is the way to go. In normal conditions, you need to make sure you are not modifying a removed object. It is very good that attempting that will result in an error. 

Can you please make a PR to discuss the implementation details?

**Comment by alshakero** [comment]
@warpech done.

**Comment by warpech** [comment]
Link to the PR: https://github.com/Palindrom/JSONPatcherProxy/pull/4

**Comment by alshakero** [comment]
@warpech thanks, sorry for not linking it.

**Comment by alshakero** [comment]
Fixed in https://github.com/Palindrom/JSONPatcherProxy/pull/4
