### ISSUE TITLE
Cleaner alternative for `ignoreAdd`

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#142]
We still have[ `filterChangedCallback`](https://github.com/Palindrom/Palindrom/blob/master/src/palindrom.js#L678-L692) that is pretty much doing nothing after we removed `ignoreAdd`.

I was thinking of introducing a clean filtering mechanism. Because day by day the need is proving to be there. 

We currently have:
```js
const proxifiedObj = this.jsonPatcherProxy.observe(
      true,
      this.filterChangedCallback.bind(this) // this is the proxy callback
);
```

And I suggest we do this:

```js
const proxifiedObj = this.jsonPatcherProxy.observe(
      true,
      patch => this.onLocalChange(this.filter(patch)) // this is the proxy callback
);
```
Where filter is simply `var filter = patch => patch` by default.  **But** people can monkey patch it and filter as they please, like:

```js
palindorm.filter = patch => patch.filter(x => x.path != '/myIgnoredProp');
```

WDYT @warpech @tomalec.

**Comment by warpech** [comment]
Yes, that looks much cleaner. Dare you prepare a benchmark to show the performance overheads? :)

**Comment by alshakero** [comment]
@warpech haha sure. On it. Should I compare against old `ignoredAdd` or against the current state? Becuase there isn't any difference with the current state, we're calling a middleware function redundantly anyways.

**Comment by warpech** [comment]
No no, I just mean compare the callback pattern vs the filtering function pattern, without our particular context of use.

**Comment by tomalec** [comment]
I really like it. It requires little bit programmatic approach. But in that case I don't see it as a big down side. Also, it's waaay more obvious and explicit on how it works and how to use it :)

**Comment by alshakero** [comment]
@warpech Thanks for the Slack explanation, it just hit me that we don't need to benchmark `Array.filter` or anything as it isn't our responsibility. If we are to offer a monkey-patchable `Palindrom.filter`.

Inside Palindrom we'll just have `filter = patch => patch`. We're not going to filter anything. But people could monkey patch `filter` with their own logic, they might use `Array.filter`, mutate the array in place and return it, or simply block all patches and return `[]`. 

Looping on the patch and calling the callback inside the filtering mechanism would be very hard to grasp. Especially from the outside. 

A pure mathematical function of `filter: patch => patch` is much easier for humans to process, at least IMO. And poeple could loop or filter as they want.

**Comment by alshakero** [comment]
Closing as done in #146.
