### ISSUE TITLE
Increase the visibility of the docs link

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#144]
Right now the link to the docs is really hard to find:

<img width="294" alt="screen shot 2017-07-25 at 16 47 00" src="https://user-images.githubusercontent.com/566463/28578107-fd808242-7158-11e7-9603-eb6bc6df8da2.png">

I'd like to propose changing it to

```
## [Documentation](https://palindrom.github.io/#/docs).
```

and move it way upper.

**Comment by alshakero** [comment]
Closing as done in https://github.com/Palindrom/Palindrom/commit/7f0d745880cdcdc0bac2f686ba27a93938b719ba.
