### ISSUE TITLE
Rewriting the Proxy

### ISSUE THREAD

**Issue by Joltrix** [Palindrom/Palindrom#151]
The latest versions of Palindrom are considered to be too slow, and being unusable due to this.

This can be observed in the Timeline app.  (I will write step by step instructions to recreate this behavior in the Timeline app below :) )

cc @stefanedqvist @Starcounter-Jack @alshakero

**Comment by Joltrix** [comment]
To recreate this behavior:

Required Apps:
SignIn - Develop branch
People - Develop branch
Notes - Master branch
Timeline - Master branch

The lag occurs when an event is being created, and the list on the client side is being updated.
Every time a note is created, it creates an entry in the timeline.

To display the timeline, Go to a person (for example admin admin)

To create a note, either click on the "create note" button in the timeline, or scroll to the bottom of the page on the "static note creator" and create notes from there
![image](https://user-images.githubusercontent.com/10708580/30058616-1434ecd6-923c-11e7-9de0-df24d529aa04.png)
A note is created when the button (circled by the yellow marker) is pressed.

Click it a few times, and also click on the "load more events" button in the timeline, until all the events are being displayed. And then try to delete a note, or add another note and the lag can be observed.

The lag can be experienced at around 20-30 (visible) events, but its a lot more obvious when there are around 100 events.

Creating a note event with 139 visible events
![lagdisplay](https://user-images.githubusercontent.com/10708580/30058858-10448112-923d-11e7-8748-60237ef82dbe.gif)


(This screenshot is taken when the timeline were displaying 134 events)
![image](https://user-images.githubusercontent.com/10708580/30058585-f704fe08-923b-11e7-8b99-cace6e51b1d4.png)

**Comment by alshakero** [comment]
Update:

This will be fixed in https://github.com/Palindrom/JSONPatcherProxy/pull/18

Down from 858ms to 32ms (31 FPS).

Before:
![befroe](https://user-images.githubusercontent.com/17054134/30156964-5793d07e-93c1-11e7-8b26-739651c01dfc.jpg)

After
![after](https://user-images.githubusercontent.com/17054134/30156963-577b5814-93c1-11e7-905f-a817cb8fca2c.jpg)

**Comment by Joltrix** [comment]
Update:
After running the same test, but this time with @alshakero's latest version of Palindrom:

(this time with 160 events rendered)
![image](https://user-images.githubusercontent.com/10708580/30216162-5c65027a-94b2-11e7-8f18-e4b27fdc9fad.png)

from 2080ms to 28!!

**Comment by tomalec** [comment]
@Joltrix  does it mean we can close this issue?

**Comment by stefanedqvist** [comment]
@tomalec  We should verify it works for Heads too. However might be that they have downgraded to a lower version. I´ll check with Henrik.

**Comment by tomalec** [comment]
I have checked manually in their app the case they shown me and got ~35% performance improvement compared to the old fast version. I've also sent an info to Peter, Fredrik and Henrik with fixed version (2.3.1.7166).

But please double check if they are satisfied with the results.

**Comment by alshakero** [comment]
Such a relief <3

**Comment by alshakero** [comment]
Closing as done.
