### ISSUE TITLE
Palindrom does not seem to ignore enumerable: false properties

### ISSUE THREAD

**Issue by miyconst** [Palindrom/Palindrom#153]
I am adding a property to an observed object by Palindrom like this:

```js
Object.defineProperty(n, "timeout", { enumerable: false, writable: true, value: 7 });
```

Since the property is marked as `enumerable: false`, I would expect it be ignored by Palindrom, but it still generates `add` patch.

cc @alshakero, @tomalec

**Comment by alshakero** [comment]
Your issue is legit. But I strongly advise you to use [this](https://palindrom.github.io/#/docs/v3.0.5/03-Filtering%20Patches).

**Comment by alshakero** [comment]
Could you tell me which version of Palindrom are you using?

**Comment by miyconst** [comment]
```
/*! Palindrom, version: 3.0.3 */
```

**Comment by miyconst** [comment]
Okay. I will try to make a small application with reproduction.

**Comment by warpech** [comment]
This looks like a serious issue because we want to rely on ignoring non-enumerable properties as the alternative to `ignoreAdd`. @miyconst were you able to reproduce it?

> But I strongly advise you to use [this](https://palindrom.github.io/#/docs/v3.0.5/03-Filtering%20Patches).

Really? I thought we have agreed that non-enumerable properties are the preferred way for Starcounter apps. In the view of a Starcounter app you are not in control of Palindrom configuration options, because these are provided in the bootstrapping middleware.

**Comment by warpech** [comment]
I think that the unnumerable property example from https://starcounter.io/dealing-puppets-ignoreadd-removal/should be added to the page https://palindrom.github.io/#/docs/v3.0.5/03-Filtering%20Patches as the alternative to `filterLocalChanges`.

**Comment by alshakero** [comment]
> Really? I thought we have agreed that non-enumerable properties are the preferred way for Starcounter apps

You're right, my bad. Here I see for myself that `defineProperty` is indeed superior https://github.com/Palindrom/Palindrom/issues/154#issuecomment-328650740.

We have a test for `filterLocalChanges`  (https://github.com/Palindrom/Palindrom/blob/master/test/specs/palindrom.filter.test.js), but we don't for `defineProperty`. I'll create an issue.

**Comment by alshakero** [comment]
[This PR](https://github.com/Starcounter/level1/pull/4280) shows that this actually works. I'll close until an example is provided. The issue of creating tests for it remains, so don't worry.

**Comment by alshakero** [comment]
Tests added in #163 and are passing.

**Comment by miyconst** [comment]
@alshakero thank you for investigation and tests development, I have nailed down the issue - see the issue linked above.
