### ISSUE TITLE
Palindrom.filterLocalChange is not safe to use

### ISSUE THREAD

**Issue by miyconst** [Palindrom/Palindrom#154]
This issue is coming from - [Palindrom does not seem to ignore enumerable: false properties](https://github.com/Palindrom/Palindrom/issues/153#issuecomment-328643806) and addressing this documentation page - [Filtering Patches](https://palindrom.github.io/#/docs/v3.0.5/03-Filtering%20Patches).

- The JS code in the code snipped is not formatted, which brings impression of half-done product.
- The `filterLocalChange` should be an event, and not a method. Otherwise there is no guarantee that someone else will not overwrite the subscription.

cc @alshakero

**Comment by alshakero** [comment]
> The JS code in the code snippet is not formatted,

Could you show me a shot?

**Comment by miyconst** [comment]
Original:

```js
const palindrom = new Palindrom({remoteUrl: window.location.href});

palindrom.filterLocalChange = function(operation) {
  if(!operation.path.startsWith('$')) {
    return operation;
  }
}
// use palindrom.obj
palindrom.obj.$someProperty = "new value"; // this change will be ignored and will not reach the server 
```

How it should be:

```js
const palindrom = new Palindrom({ remoteUrl: window.location.href });

palindrom.filterLocalChange = function (operation) {
    if (!operation.path.startsWith('$')) {
        return operation;
    }
}
// use palindrom.obj
palindrom.obj.$someProperty = "new value"; // this change will be ignored and will not reach the server
```

**Comment by alshakero** [comment]
> The filterLocalChange should be an event, and not a method. Otherwise there is no guarantee that someone else will not overwrite the subscription.

Good point, but Palindrom is a pure Javascript class, doesn't have DOM events. And `ignoreAdd`, which this function evolved from, could have been also abused in the same manner. Though two wrongs don't make a right.

I'd say `addFilter()` API would be do. Like:

```js
palindrom.addFilter(function(operation) {
// your filtering logic
});
```

**Comment by warpech** [comment]
> The filterLocalChange should be an event, and not a method. Otherwise there is no guarantee that someone else will not overwrite the subscription.

It is a bad practice to overwrite a method instead of calling `super`. You can do:

```js
var old = palindrom.filterLocalChange;
palindrom.filterLocalChange = function(operation) {
    operation = old.call(palindrom, operation); //make sure you don't overwrite other filters
    if (!operation.path.startsWith('$')) {
        return operation;
    }
}
```

**Comment by tomalec** [comment]
> The filterLocalChange should be an event, and not a method. Otherwise there is no guarantee that someone else will not overwrite the subscription.

We removed events from Palindrom in purpose, to make it more lightweight. So `filterLocalChange` is not a way to subscribe, it's just a filter method. Alos, I'd say overwriting things is a pretty natural thing in JS world. You can overwrite `Array.prototype.sort` if you want. Setting/overwriting `XMLHttpRequest.onready` is also basic standard way to inject some action in the lifecycle of a thing.

> I'd say `addFilter()` API would be do. Like:

Then we will need also `removeFilter` so we are getting closer to implementing `add-/removeEventListener` API back agin. I don't see a big reason to implement such API, especially given, HTMLElement (`<palindrom-client>`) has it for free.

If we really need to make it non-everwritable, I'd add it as a constructor parameter. But I still don't see a big value and reason of doing so. (As long as we have `defineProperty` behavior in place, and remember about `super`)

**Comment by warpech** [comment]
@miyconst thanks for reporting, but as you can see we are categorizing it as "Won't fix". Is there some actual need to re-consider it or can this request be archived?

**Comment by miyconst** [comment]
Since Palindrom is a standalone product, we can fix the issue as won't fix.
