### ISSUE TITLE
Firefox: Redirecting to external URL or closing a tab displays disconnection warning

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#160]
> Moved from https://github.com/Palindrom/palindrom-redirect/issues/3

## Steps to reproduce

In Firefox, use an external link in a Palindrom app, e.g.

```
<a href="http://google.com" target="_top">Google</a>
```

or just close a tab that is running a Palindrom app in Firefox.

## Expected

No error should be shown

## Actual

For a second, you see a red "Connection error" at the top ot the screen.

**Comment by alshakero** [comment]
Should be fixed in https://github.com/Palindrom/Palindrom/pull/168.
