### ISSUE TITLE
Polymer.set is incompatible with enumerable: false properties

### ISSUE THREAD

**Issue by miyconst** [Palindrom/Palindrom#164]
Coming after investigation of - [Palindrom does not seem to ignore enumerable: false properties](https://github.com/Palindrom/Palindrom/issues/153).

I have nailed down the issue. It seems like `Polymer.set` API breaks the things app.

### This example works fine

```js
Object.defineProperty(template.model, "ClientSideValue", {
    value: "Value",
    enumerable: false,
    writable: true
});

template.notifyPath("model.ClientSideValue", template.ClientSideValue);
```

### But this one sends an `add` patch to the server

```js
Object.defineProperty(template.model, "ClientSideValue", {
    enumerable: false,
    writable: true
});

template.set("model.ClientSideValue", "value");
```

@alshakero is there anything we can do about it?

**Comment by alshakero** [comment]
Of course. `template.set("model.ClientSideValue", "value");` overrides the first part.

The good practise that works with every side is to create a non-enumerable sub-**object** and dumb whatever you want inside it. 
```js
Object.defineProperty(template.model, "myLocalNonSyncedObject", {
    enumerable: false,
    value: {},
    writable: true
});
template.set("model.myLocalNonSyncedObject.myIgnoredProp", "ignoredValue");
```

**Comment by alshakero** [comment]
And thank you for assigning me, it makes my life much easier.

**Comment by warpech** [comment]
It is good it this also is mentioned on our Docs page about ignoring changes.

**Comment by alshakero** [comment]
Created https://github.com/Palindrom/Palindrom/issues/165

**Comment by miyconst** [comment]
>The good practise that works with every side is to create a non-enumerable sub-object and dumb whatever you want inside it.

Yeah.. the situation I had was an array of items, where each item has to save it's own client side value. So, adding a sub-object would be even more complicated than using `notifyPath` instead of `set`.

**Comment by miyconst** [comment]
Anyway, thank you for the answer, I close the issue as answered question. We should not fight with Polymer trying to fix/remake it's `set` function behavior.

**Comment by alshakero** [comment]
I guess in such case `filterLocalChange` is your friend.

**Comment by miyconst** [comment]
>I guess in such case `filterLocalChange` is your friend.

Is my biggest enemy. If I use it, what prevents other app developers from using it? Means, I can't guarantee my partial will work when there are partials from other pages.

**Comment by alshakero** [comment]
Didn't @warpech[ show a way](https://github.com/Palindrom/Palindrom/issues/154#issuecomment-332346119) that overcomes this issue?

**Comment by miyconst** [comment]
Well.. yes and no.

- There is no guarantee that someone else will follow this principle.
- It is also required to track whether required function already applied to Palindrom (same partial may be loaded multiple times). Means some kind of a global state has to be used.

I prefer to keep a partial view-model as a self sufficient black box. When it's detached, nothing left after it.

**Comment by alshakero** [comment]
> When it's detached, nothing left after it.

Solid point

**Comment by warpech** [comment]
I agree with @miyconst, that's why I think non-enumerable properties are a superior solution in case of Starcounter views.
