### ISSUE TITLE
⏰ Validate numerics range in incoming and outgoing data

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#170]
Some out-of-range (`n > Number.MAX_SAFE_INTEGER`, `n < Number.MIN_SAFE_INTEGER`) numbers that come from non-JS endpoints could break Javascript's side (Palindrom). We need to check incoming data for those.

**Comment by alshakero** [comment]
Done in https://github.com/Palindrom/Palindrom/pull/171

**Comment by warpech** [comment]
Before we can move it from "Announce and release" to "Done", please add an info about it to the Docs.

**Comment by alshakero** [comment]
Ah, good point! I guess I shouldn't have moved it to announce and released in the first place. I moved it back. Please do whatever you think is right if you don't agree.

**Comment by alshakero** [comment]
This is now documented. I didn't PR because I'm releasing a new version that fixes a bug https://github.com/Palindrom/Palindrom/issues/174. Since docs are non-code stuff, they can be reviewed later.

[Here are the docs](https://github.com/Palindrom/Palindrom/blob/master/docs/07-_Numbers.md), please close the issue if you think they're alright.

**Comment by warpech** [comment]
Maybe a more technical explanation could be used? Like:

> It is not a limitation of JSON, but of JavaScript, that all numbers are stored in memory as float64 (equivalent to `Double` in C#). This means that numbers larger than +/- **9007199254740991** cannot be used in JavaScript without losing precision.

**Comment by alshakero** [comment]
I created a quick PR https://github.com/Palindrom/Palindrom/pull/176

**Comment by alshakero** [comment]
Closing as done!
