### ISSUE TITLE
[Palindrom 3.0.7] Uncaught (in promise) Error 

### ISSUE THREAD

**Issue by Mihaiii** [Palindrom/Palindrom#174]
Steps to reproduce:
1. Use SC 2.3.1.7717 (current latest RC)
2. Run `staradmin start db`
3. Navigate to `http://localhost:8181/#/databases`
4. Run `staradmin kill all`

In console you'll see `Uncaught (in promise) Error: Network Error`.
If you replace in "C:\Program Files\Starcounter\ClientFiles\StaticFiles\sys\Palindrom\dist\palindrom.js" Palindrom 3.0.7 with Palindrom 3.0.6, then everything is ok.

@alshakero Could you please have a look?

**Comment by alshakero** [comment]
Thank you so much! This should be fixed in https://github.com/Palindrom/Palindrom/commit/a490ff4be371e31e882129abfc1d8c01558ff9b2

**Comment by Mihaiii** [comment]
Tested on local after taking that version!
Closed as fixed.
