### ISSUE TITLE
Ditch Axios for pure fetch api since ES6 is assumed

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#175]
This saves us a couple kilobytes and uses native API.

**Comment by alshakero** [comment]
Before going for this, I did some research to avoid jumping any guns. And for the meantime Axios remains superior over fetch. Here is the article that changed my mind. 

https://medium.com/@shahata/why-i-wont-be-using-fetch-api-in-my-apps-6900e6c6fe78

It's worth mentioning that I did it already and it's working and the bundle went from **45K to 36K**, but tests will take at least two days to migrate and I thought I need more information before investing such amount of time.

In conclusion:

**Pros of `fetch`:**

1. Bundle is 10KB less.
2. Works everywhere we need.
3. Less bug-prone than a 3rd part library.

**Cons:**
1. No timeouts which I plan to implement soon.
2. No request cancelation.
3. HTTP errors aren't easy to catch. They all call `then` not `catch` and one has to check the status and decide.
4. Tests will take 2 days to migrate.
5. No business need for now.


So I'll freeze this issue and will come back to it later. Please let me know if you think that I should still do it.

**Comment by tomalec** [comment]
Implemented in https://github.com/Palindrom/Palindrom/pull/227
Released in [6.1.0](https://github.com/Palindrom/Palindrom/releases/tag/6.1.0)
