### ISSUE TITLE
Protect from common security threats

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#182]
@alshakero informed that React issues a warning when developer writes insecure code, for example `<a target="_blank">` without `rel="noopener noreferrer"` (see: [Target="_blank" - the most underestimated vulnerability ever](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/))

Should PalindromDOM do the same and have a warning/error when the developer does that?

cc @alshakero, @tomalec

**Comment by alshakero** [comment]
I think this particular case should definitely be done. It's high risk and easy + efficient to detect.

```js
const noOpenerErrorExists = !!document.querySelector('a[href="_blank"]:not([rel*="noopener"])')
```

**Comment by tomalec** [comment]
> It's high risk and easy + efficient to detect.

The question is when :) especially given in Starcounter apps we are building document pretty dynamically at runtime.

**Comment by warpech** [comment]
I believe it should be:

```js
const rel = target.getAttribute("rel");
const noOpenerErrorExists = rel && rel.indexOf("noopener") > -1
```

and placed somewhere here: https://github.com/Palindrom/Palindrom/blob/f98707b728cd8d4b3a37cef4885848fef8562561/src/palindrom-dom.js#L163

**Comment by alshakero** [comment]
Then the warning would only show upon user's click. Is this sufficient?

**Comment by warpech** [comment]
You saw it first in React. How is it done there?

I think it is sufficient to show a [`confirm`](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) upon user's click.

**Comment by alshakero** [comment]
@warpech yes, but in React you have a `DEV` flag that allows you to do all kinds of inefficient verifications in the app before you release with `PROD`. They don't have the efficiency question to have the answer to it.

I agree with the `confirm` thing, but what if the dev was interested in `opener` in their target URL? I think we should offer an opt-out.

**Comment by alshakero** [comment]
Wow 😮 I didn't close this!

**Comment by warpech** [comment]
Perhaps we should use a more explicit attriubute name like `data-palindrom-allow-insecure`.

I think that the message in the `confirm` should be targeted at the developer, so it can simply be:

if `data-palindrom-allow-insecure` is set, we just redirect,
if `data-palindrom-allow-insecure` isn't set, we confirm with the message `Warning! This link opens a window in an insecure way, allowing the scripts in the new window to access the window that opened it. Add `rel="noopener"` attribute to the <a> element to open links without granting the access or add `data-palindrom-allow-insecure` attribute to that element to disable this message"

**Comment by tomalec** [comment]
I'm just afraid that dev will not click on all click they create or their app create with `target="_blank"`, so they will totally miss the warning and we will end up showing that message to the end users., who will only get scared by the message.

**Comment by tomalec** [comment]
I'm just afraid that dev will not click on all click they create or their app create with `target="_blank"`, so they will totally miss the warning and we will end up showing that message to the end users., who will only get scared by the message.

**Comment by alshakero** [comment]
Day by day the need for some DEBUG flag is increasing.

**Comment by tomalec** [comment]
What about adding it to `starcounter-debug-aid`? There we could do even do `MutationObserver` on everything 😈

**Comment by alshakero** [comment]
I think this is a great idea.

**Comment by warpech** [comment]
I agree with adding it to health checks in `starcounter-debug-aid`, that's a great idea.

I dislike the idea for any more DEBUG flags, because (1) it leads to spaghetti code with too many side effects of a single value, (2) developers are too lazy or uninformed to turn this flag on or off.

**Comment by alshakero** [comment]
So I'll close this in favour of this https://github.com/Starcounter/DevTools/issues/73
