### ISSUE TITLE
Apply @tomalec's review of PR #172

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#186]
@alshakero, @tomalec has left few interesting notes in https://github.com/Palindrom/Palindrom/pull/172#pullrequestreview-80680495. Please make sure to not miss it - implement it or just respond to it.

**Comment by alshakero** [comment]
@warpech I didn't forget about it all. But I'm really busy with many higher priority things. I'll end today with it.

**Comment by alshakero** [comment]
Done in https://github.com/Palindrom/Palindrom/commit/9d1e0e1a42db315ed7af86c294ae9a7f52237303

Address and responded.

**Comment by alshakero** [comment]
Feel free to reopen if you have any concerns.
