### ISSUE TITLE
PalindromDOM should ignore `download` attribute

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#189]
PalindromDOM should not intercept links to downloadable resources that are marked with `download` attribute.

This was a problem reported in https://github.com/Starcounter/level1/issues/3364

Current workaround: use `target="_blank"` on such link.

**Comment by alshakero** [comment]
PR in https://github.com/Palindrom/Palindrom/issues/189

**Comment by alshakero** [comment]
Closing as done in https://github.com/Palindrom/Palindrom/pull/190

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Palindrom/Palindrom/releases/tag/v3.1.0
- published on npm https://www.npmjs.com/package/palindrom
- included in a Finished release of SCF https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.1.1
