### ISSUE TITLE
Rename the docs page "Filtering Patches"

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#192]
The page ["Filtering Patches"](https://palindrom.github.io/docs/03-_Filtering%20Patches/) is mostly about ignoring patches, not filtering.

I suggest it is renamed to "Filtering and ignoring changes".

**Comment by alshakero** [comment]
Closing as done in https://github.com/Palindrom/Palindrom/commit/c8bbb61cf29abe9880d3032cc86ec68f317c4439
