### ISSUE TITLE
Call onPatchReceived callback before validation

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#193]
Since there is a ~~`onPatchApplied`~~ `onRemoteChange`  that signifies a patch arrival + validation pass + applying, it makes sense to make `onPatchRecieved` a kind of a network signal rather than a Palindorm signal. This will also allow subscribers to see patches that are received but failed validation.

Fixes: https://github.com/Starcounter/DevTools/issues/64

**Comment by warpech** [comment]
I cannot find `onPatchApplied`. Where is that?

In Palindrom I can see the following relevant callbacks:

- `onRemoteChange` - Helper callback triggered each time a change is received from the server and applied.
- `onPatchReceived` - Helper callback triggered each time a JSON-patch is received

At what point does the current `onPatchReceived` abandon the execution resulting in the failing patch not showing in DevTools?

Would it solve the problem if you move triggering `onPatchReceived` to the top of the `handleRemoteChange`?

**Comment by alshakero** [comment]
My bad. I meant onRemoteChange, that’s because palindrom-client calls it so. 

> would it solve... 

Yes. I think so.

**Comment by alshakero** [comment]
PR in https://github.com/Palindrom/Palindrom/pull/198
