### ISSUE TITLE
Change library definition 

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#196]
I don't really like the current definition, here is my proposal:

Change it form 

> Palindrom is a library for two-way data binding between local and remote JSON models, using JSON-Patch, with optional Operational Transformation, via HTTP or WebSocket.

to 
> Palindrom is a library for two-way data binding between local and remote JSON models. It uses JSON-Patch for data updates and Operational Transformation for versioning and data consistency. It operates via HTTP or WebSocket or both.

WDYT @warpech @tomalec @Mackiovello

**Comment by warpech** [comment]
Looks very good!

**Comment by alshakero** [comment]
Here is your answer @Mackiovello 😃

**Comment by alshakero** [comment]
Done in https://github.com/Palindrom/Palindrom/commit/6fffa6753c812a98d575bc24919a85ba5108089c

**Comment by tomalec** [comment]
I've updated the repo description (https://github.com/Palindrom/Palindrom) as well

**Comment by alshakero** [comment]
Forgot about that. Thanks a lot.
