### ISSUE TITLE
Remove the demo pages (labs)

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#205]
Today it was proposed by @alshakero and me to remove demos of Palindrom and `palindrom-client` because they are hard to maintain. 

This would obsolete the following issues:

- https://github.com/Palindrom/Palindrom/issues/115
- https://github.com/Palindrom/palindrom-client/issues/65
- https://github.com/Palindrom/palindrom-client/issues/21

@tomalec WDYT?

**Comment by warpech** [comment]
When I recall from memory, I've spent more time fixing the demo mock server than actually using the demo to ease the development. For me, the idea of a client-side demo page that uses a mock server is not sustainable.

I checked with our "competition":

- https://github.com/derbyjs/racer - doesn't have a demo page, has example files that you need to run on your server
- https://socket.io/ - has a demo page that uses a real server not a mockup server
- https://github.com/primus/primus - no demo
- https://github.com/sockjs/sockjs-client - no demo
- https://github.com/topcloud/socketcluster - no demo
- https://faye.jcoglan.com/ - no demo
- https://github.com/josephg/ShareJS - no demo
- https://github.com/share/sharedb - doesn't have a demo page, has example files that you need to run on your server

**Comment by tomalec** [comment]
Ok, I feel conviced now. Thanks. 

However, i get an idea to connect to inside.starcounrer.com or smth. But maybe it's not worth it. It's also a pitty we have no sample code to be used on ther server.

**Comment by alshakero** [comment]
Regarding Palindrom, I'll just delete `gh-pages` branch. Is this correct?

**Comment by alshakero** [comment]
Done by deleting `gh-pages` branch.
