### ISSUE TITLE
Connection error - clicking on Do not reload doesn't work

### ISSUE THREAD

**Issue by habib535** [Palindrom/Palindrom#206]
My developer tools is not opened but when an error appears I want to see it in the console but Palindrom reload the page despite clicking on don't reload button.

![reloadclick](https://user-images.githubusercontent.com/2991381/37027749-8102ca6a-2132-11e8-9d17-7001f74e5d0c.gif)

**Comment by warpech** [comment]
Related (but not the same?): https://github.com/Palindrom/palindrom-client/issues/62

cc @alshakero

**Comment by alshakero** [comment]
True. Related, these issues both are fixed already and will be released in the next release of `palindrom-client`.

**Comment by alshakero** [comment]
Released 6.0.0 and it fixes this. It will be in StarcounterClientFiles soon (2-3) days.
