### ISSUE TITLE
Changing server side Palindrom design towards a faster first meaningful paint

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#207]
### Intro 

First, if you're not fimiliar with the term "first meaningful paint", please check this [link](https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint). In short, the link says: 
> This audit identifies the time at which the user feels that the primary content of the page is visible".

In other words, how long it takes after navigation for the app to paint something meaningful.

Second, I'd like to note that all the time measurements mentioned here are under "Slow 3G" network and throttled proccessor emulation. There are many reasons to measure under emulated slower devices and networks, of which the most interesting to us is that it gives very consistent results between re-runs. Because Slow 3G and 20% of your CPU are always easy to acheive for your machine, even if something is running in the background or something.

In Web Platform Team, we've been discussing performance impovements for the last couple weeks, we experimented a lot, but we only found one considerable imporvement to drop the first meaningful paint time, from ~12000ms to ~7000ms. That's ~164% faster. This is great but much more work can be done. And now we need to work on the server side. 

There is always more corners to cut in the client side, but what I'm proposing here theorotically provides a much more considerable improvement than cutting corners on the client-side files. And obviously why not do both. 

### The current setup

Current Palindrom setup is like this:
![image](https://user-images.githubusercontent.com/17054134/37045957-760f9f54-2167-11e8-918b-3c404a30a0dc.png)

As you can see, we're serially doing
```sh
HTTP GET -> HTTP AJAX GET (for the first model) -> HTTP AJAX GET (for the first view) -> Render
```

### What I propose is we can do this:

![image](https://user-images.githubusercontent.com/17054134/37045942-6bb99758-2167-11e8-8d23-9bca87c078a6.png)

This will mean that we do:

```sh
HTTP GET -> HTTP AJAX GET (for the first view) -> Render
```

This collapses the first two requests into one. This might seem like one request shorter which is by itself is an improvement, but it's more than that because this will allow the browser to work in parallel. 

See the current requests waterfall:
![current timing](https://user-images.githubusercontent.com/17054134/37046381-862d94e4-2168-11e8-952c-86ec5d90d7ea.png)

See the proposed request waterfall: 
![proposed timing](https://user-images.githubusercontent.com/17054134/37046352-704dcc0c-2168-11e8-9d54-f5520cbff014.png)

Theoretically, it's 6000ms faster! But to be realistic let's assume half of that. 3000ms is good enough.

### Proposed implementation

There is a constraint that we need to consider before going ahead. The app-shell should be 100% cachable static HTML. We don't stick to this constraint in our current setup, but we need that for Starcounter to be [PWA](https://developers.google.com/web/progressive-web-apps/) friendly. What breaks the contraint for the mean time is the inlined server-generated session ID. `0B7C66A45336FA9530000020` in the following example.
```html
<palindrom-client ref="palindrom-root" remote-url="/__default/0B7C66A45336FA9530000020"></palindrom-client>
```

Currently, SC server responds with the HTML [here](https://github.com/Starcounter/level1/blob/develop/src/Starcounter/Middleware/PartialToStandaloneHtmlProvider.cs). In this link to `PartialToStandaloneHtmlProvider`, there are `{0} (title)`, `{1} (session ID)`. This string is rendered when you visit any routed URL.

I suggest that we create another special URL say (`/__bootstrap.js`) in Starcounter that also renders a string template. We (web-platform-team) can decide what's the template is, just like we decide the current one in `PartialToStandaloneHtmlProvider`. But what we need from `level1` is to provide us with the session ID in `{0}` and initial JSON model in `{1}`. The same way it provides us with the session ID in `PartialToStandaloneHtmlProvider`. For easier understanding, navigating to `/__bootstrap.js` should yield:

```json
{  
   "sessionID":"0B7C66A45336FA9530000020",
   "initialJSON":{  
      "_ver#c$":0,
      "_ver#s":0,
      "KitchenSink_0":{  
         "Html":"/KitchenSink/MasterPage.html",
         "NavPage":{  
            "KitchenSink_0":{  
               "Html":"/KitchenSink/NavPage.html"
            }
         },
         "CurrentPage":{  
            "KitchenSink_0":{  
               "Html":"/KitchenSink/MainPage.html"
            }
         }
      }
   }
}
```
Given the template is
```js
{
    "sessionID":"{0}",
    "InitialJSON": "{1}"
}
```

This url `/__bootstrap.js` will be requested from the app-shell like
```js
<script src="/__bootstrap.js" async>
```

As you can see, the session ID is no longer in the app-shell, making it cachable. And `/__bootstrap.js` will be requested as one of many parallel requests. Which will result in a much earlier first meaningful paint.

Thanks for reading this long issue!

**Comment by Mihaiii** [comment]
Hi!

I have a question which might be a little bit offtopic, but I don't know where is the official issue for server side Palindrom.

So right now when we send a patch, the whole view-model get reevaluated (someone please correct me if this is inaccurate). Would a server side Palindrom fix this "problem", meaning that a patch with only what is changed will be sent back without reevaluating everything? If yes, that would be awesome!

I'm just asking, I'm not ever sure if it's possible and the answer - whatever it might be - would help me better understand the purpose of server side Palindrom.

Thanks,

**Comment by Mihaiii** [comment]
Nevermind, it would have to be a complicated selective reevaluation because of computed properties.

**Comment by warpech** [comment]
@Mihaiii, yes, the whole session can update in real-time and some of the properties come from getters so obviously then need to be reevaluated on the server. But let's not discuss it here because that's entirely off-topic.

----

@alshakero is working on an updated version of the above draft. It will be published here as a link to Google Docs.

**Comment by alshakero** [comment]
@warpech here is the draft https://docs.google.com/document/d/1wvVWdantUsaPJOx_SgXdMxsqfmp5OUwqjsyVQuoupeo/edit?usp=sharing

**Comment by warpech** [comment]
@alshakero is this issue obsoleted by https://github.com/Palindrom/Palindrom/issues/61? If yes, feel free to close.

**Comment by alshakero** [comment]
Yes it is. Thanks.
