### ISSUE TITLE
consider http://orbitjs.com/

### ISSUE THREAD

**Issue by COLABORATI** [Palindrom/Palindrom#211]
please look at http://orbitjs.com/ and consider using that.

**Comment by warpech** [comment]
Closing as Palindrom is not really a project that could *use* OrbitJS. OrbitJS seems to be a more heavyweight, though more flexible, project.

Palindrom is opinionated in a way that it uses standards JSON + JSON Patch over HTTP + WebSocket to synchronize a state object between two peers.

Thanks for your contribution anyway. Is there something in particular that you wanted to suggest considering from OrbitJS?
