### ISSUE TITLE
palindrom-errors uses window object which is not available in NodeJs

### ISSUE THREAD

**Issue by miyconst** [Palindrom/Palindrom#219]
[Here](https://github.com/Palindrom/Palindrom/blob/master/src/palindrom-errors.js#L16) `palindrom-errors.js` uses `window.location.href` as a default value for a parameter.

This is not applicable when running inside NodeJs, since the global `window` object is not available.

```js
constructor(message, side, url = window.location.href, connectionType) {
```

**Comment by warpech** [comment]
I suggest to remove the default value at all from the constructor and pass `window.location.href` from elsewhere.
