### ISSUE TITLE
Palindrom breaks user session when response status code is 404

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#220]
Palindrom breaks user session when the HTTP response status code is 404, because any status beyond the range >= 200, < 300 is considered a promise error.

I think this is wrong, because from the usability perspective, a 404 Not Found or 403 Forbidden page may still be interactive and navigable by a user.

Until we have a better solution, I propose to treat 4xx status codes as non-fatal and 5xx status codes as fatal.

cc @miyconst, @malx122, @kegor, @tomalec 

---

This is urgent because it is needed to properly implement 404 pages.

**Comment by miyconst** [comment]
I agree.
