### ISSUE TITLE
Cleanup and house keeping

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#224]
This is an umbrella issue for Palindrom cleanup:

The things I propose to do are:

### Step 1:

- Clean up as many callbacks as possible from the codebase in `palindrom.js`, now it's quite convoluted, most of the time needlessly. Like `connectToRemote`, `reconnectionFn`, `bootstrap`. `makeInitialConnection`, `makeReconnection` most of these can be promisified to become cleaner or entirely removed. 
- Move `PalindromNetworkChannel`, `Reconnector`, `Heartbeat` to separate files since we're using Webpack anyways.
- Merge `establish` and `reestablish`. 
- Remove deprecated `changeState`.
- Move `closeWsIfNeeded` from a function to a `_method`. 
- Remove deprecated `options.callback`. 
- Remove deprecated `ignoreAdd`. 
- Remove never used `showWarning`.
- Move `sendPatches` from a function to a `_method`. 

I'll commit for every one of those for easier review.

### Step 2:
Now that we cleaned up with the same tests and we know we have a working, clean codebase, we move to step 2:

- Implement #175 and update the tests accordingly.

**Comment by warpech** [comment]
Please only implement step 1, I think that we will not have time for step 2 now.

**Comment by alshakero** [comment]
All of the steps are done. Just some final polishing and conflict resolving is needed. All pushed here https://github.com/Palindrom/Palindrom/pull/227

**Comment by warpech** [comment]
@tomalec can you please finish this issue? The PR https://github.com/Palindrom/Palindrom/pull/227 is close to finishing.
