### ISSUE TITLE
Create `closeConnection` API method

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#233]
> Anyway, a new method is the Palindrom API was not expected in a PR that only does a refactor. Also there is no test for it and no entry in `docs/`

Please remove it and make an issue that requests adding it.

_Originally posted by @warpech in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjMxNTg4NDA5/pull_request_reviews/more_threads_

**Comment by tomalec** [comment]
@alshakero your link is broken, I think you meant https://github.com/Palindrom/Palindrom/pull/227#discussion_r279332101

What would be the rationale for adding it? Gentle disconnection once `<palindrom-client>` is disconnected, to avoid hacks like https://github.com/Palindrom/palindrom-client/blob/master/palindrom-client.html#L144

**Comment by tomalec** [comment]
Implemented in #227
Released in [@6.1.0](https://github.com/Palindrom/Palindrom/releases/tag/6.1.0)
