### ISSUE TITLE
Use `palindrom-dom` as the default entry point in Node, do not use the `browser` field

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#261]
Right now, the NPM package uses `src/palindrom` as the `main` entry point and `src/palindrom-dom.js` as the `browser` entry point.

`browser` is considered legacy and problematic. See:
- https://github.com/webpack/webpack/issues/7646 (by @webreflection)
- https://github.com/webpack/webpack/issues/4674
- https://github.com/gatsbyjs/gatsby/issues/3192

One of the problems is that `browser` is incompatible with the 3rd alternative entry point `module.` There is no 4th kind of entry point (`module-browser`).

Note: this seems to be Webpack's order of preference: `browser` > `module` > `main`.

Several other libraries have also stopped using `browser`, for example https://github.com/blockstack/blockstack.js/pull/621

**Comment by tomalec** [comment]
WDYT about separating PalindromDom to a separate repo/module? It will make such problems not relevant any more.

**Comment by warpech** [comment]
That would also be a solution but might backfire on us with maintenance hell.

Another solution is to keep `src/palindrom-dom.js` as the entry point, but do not use default exports. Like these guys: 

- https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/
- https://palantir.github.io/tslint/rules/no-default-export/
- https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad
- https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html

**Comment by tomalec** [comment]
I vote for no "defaults".

**Comment by tomalec** [comment]
Implemented in #261
Released in [@6.2.0](https://github.com/Palindrom/Palindrom/releases/tag/v6.2.0)
