### ISSUE TITLE
PuppetJs logo

### ISSUE THREAD

**Issue by tomalec** [Palindrom/Palindrom#34]
puppet-bunny is funny :)
![puppet-bunny](http://puppetjs.github.io/PuppetJs/lab/polymer/components/puppet.png)
But I don't know how to apply MIKI Yoshihito (CC BY 2.0) to a logo.

**Comment by alshakero** [comment]
![logo](https://cloud.githubusercontent.com/assets/17054134/21233888/2e5439ac-c2f1-11e6-8d82-e1ee8d7928ae.png)

What do you think?

**Comment by miyconst** [comment]
@alshakero thank you for the nice picture. Currently we are looking for a better name for the library, because PuppetJs is confusing and not self descriptive.

**Comment by alshakero** [comment]
Logo proposals, if you don't know about the name, please go to #83 

![image](https://cloud.githubusercontent.com/assets/17054134/22642800/6c3223bc-ec5c-11e6-90c1-eb6e4fa3675a.png)

![image](https://cloud.githubusercontent.com/assets/17054134/22642815/769c35ae-ec5c-11e6-8590-730e73f8abd9.png)

![image](https://cloud.githubusercontent.com/assets/17054134/22642845/963748c2-ec5c-11e6-8b84-9f9d201839b2.png)

![image](https://cloud.githubusercontent.com/assets/17054134/22642853/9bec4646-ec5c-11e6-872f-1d9ada066da3.png)

**Comment by alshakero** [comment]
![image](https://cloud.githubusercontent.com/assets/17054134/22642815/769c35ae-ec5c-11e6-8590-730e73f8abd9.png)

**Comment by alshakero** [comment]
![image](https://cloud.githubusercontent.com/assets/17054134/22642845/963748c2-ec5c-11e6-8b84-9f9d201839b2.png)

**Comment by alshakero** [comment]
![image](https://cloud.githubusercontent.com/assets/17054134/22642853/9bec4646-ec5c-11e6-872f-1d9ada066da3.png)

**Comment by tomalec** [comment]
As we have finally agreed on new name https://github.com/PuppetJs/PuppetJs/issues/83, we can come back to the topic of logo.

Personally, I do like  https://github.com/PuppetJs/PuppetJs/issues/34#issuecomment-277638122 for the color palette, simplicity and overall good looking. However, if I could be picky, I'd say that there is nothing palindrome related in it ;)

**Comment by warpech** [comment]
Yes, maybe let's use some mirror looking font? Like

<img width="1418" alt="screen shot 2017-02-24 at 13 51 31" src="https://cloud.githubusercontent.com/assets/566463/23304129/6b663992-fa98-11e6-964c-667bf60213fd.png">

![image](https://cloud.githubusercontent.com/assets/566463/23304158/88741978-fa98-11e6-8493-6dad4ded4a4c.png)

![image](https://cloud.githubusercontent.com/assets/566463/23304188/b218ff14-fa98-11e6-91b5-b8bbf9478255.png)

**Comment by alshakero** [comment]
![image](https://cloud.githubusercontent.com/assets/17054134/23304569/c545eba4-fa9a-11e6-95d8-1efa0e5e44ef.png)

**Comment by warpech** [comment]
L and N look weird to me, but otherwise it is very interesting

**Comment by warpech** [comment]
Maybe make few letters look normal, as M. And keep just few letters mirrored?

**Comment by alshakero** [comment]
I was thinking maybe just use the O. It looks cool alone, I'll propose a couple in couple minutes.

**Comment by alshakero** [comment]
![image](https://cloud.githubusercontent.com/assets/17054134/23305375/cacd3c5e-fa9e-11e6-9a54-4c62c7fca183.png)


![image](https://cloud.githubusercontent.com/assets/17054134/23305398/e4c857d8-fa9e-11e6-9d37-8b74392bd596.png)

**Comment by alshakero** [comment]
This will look a little better when I vectorize it.

**Comment by Joltrix** [comment]
>  was thinking maybe just use the O. It looks cool alone, 

Yeah! just have it like: PALINDROOM (and only use that double O) and have the rest of the letters normal?

cause my first impressions of this is: "too much" and the P and D are quite hard to read, but maybe that's just me xD

**Comment by warpech** [comment]
Same here, can you try to make P, D, R normal?

**Comment by alshakero** [comment]
![image](https://cloud.githubusercontent.com/assets/17054134/23306087/0ce29564-faa2-11e6-96b1-e4359aae3df0.png)

**Comment by alshakero** [comment]
Small logo when next to normal text
![image](https://cloud.githubusercontent.com/assets/17054134/23306134/560b5618-faa2-11e6-8010-079c7747f663.png)

**Comment by warpech** [comment]
I like both, but they could use more color :)

**Comment by Joltrix** [comment]
Yeah! I also like both! :D I wonder if it would look better, if (in the first picture, with the black background), switched the background color, and the font color,

and perhaps switch the font a bit as well? 

Cause: Most of the letters are very.. "straight", for example "A L I M" and even the R and D have "more straight lines", while P looks really "curvy",

so, maybe a font where all the letters kind of fit the same "standard", and then have that double O and maybe even the double A?

But, even if not, I really liked both of them, So I have no complaints were you to simply choose one of the two existing ones :) !

**Comment by tomalec** [comment]
I like to look of double O in https://github.com/PuppetJs/PuppetJs/issues/34#issuecomment-282298179 especially that it looks like an optical illusion of a cylinder skewed right and left at the same time, which is perfectly aligned with what we does

**Comment by alshakero** [comment]
@Joltrix the issue it isn't a font, it's a collection of drawn things. That's why I don't really like it. Isn't 100% neat. Needs a bit perfecting. I'll put some real work and come back with something isn't sketchy.

**Comment by Joltrix** [comment]
> especially that it looks like an optical illusion of a cylinder 

I hadn't even thought of that until you mentioned it! But you're right! I suddenly like it more haha

**Comment by alshakero** [comment]
Light

![image](https://cloud.githubusercontent.com/assets/17054134/23307206/06a9f368-faa7-11e6-875a-b938ccd3e9ee.png)


Dark
![image](https://cloud.githubusercontent.com/assets/17054134/23307199/fdbc4274-faa6-11e6-8138-d8509ea4f03c.png)

**Comment by alshakero** [comment]
A bit harder color:
![image](https://cloud.githubusercontent.com/assets/17054134/23307393/ab4995b8-faa7-11e6-880d-e39d6b0a4335.png)

**Comment by Mackiovello** [comment]
The bright one with the harder color is really neat! Nice job @alshakero

**Comment by alshakero** [comment]
@Mackiovello thanks a lot, I like it the most too!

**Comment by alshakero** [comment]
Vote: 

![image](https://cloud.githubusercontent.com/assets/17054134/23307710/ccc5f10e-faa8-11e6-9a31-e532b8053b88.png)

**Comment by alshakero** [comment]
![image](https://cloud.githubusercontent.com/assets/17054134/23307729/dd3d62f6-faa8-11e6-9a7d-a4be0327eaf9.png)

**Comment by tomalec** [comment]
It seems we can finally close this issue :)
