### ISSUE TITLE
debug mode collides with JSON Patch versioning

### ISSUE THREAD

**Issue by tomalec** [Palindrom/Palindrom#36]
[`validatePatches`](https://github.com/PuppetJs/PuppetJs/blob/master/src/puppet.js#L351) is being called before operation objects are shifted from entire JSON Patch sequence, so it complains about patching non-existing nodes.

Probably it may not be an issue when we separate Puppet engine, from validation, and from JSON Patch queues, that we already thought about.

**Comment by miyconst** [comment]
@tomalec is this issue still relevant? It looks like the validation has been moved to https://github.com/Starcounter-Jack/JSON-Patch/blob/master/src/json-patch-duplex.js#L622.

**Comment by tomalec** [comment]
I'm not sure if it's still reproducible, but we still validate on apply https://github.com/Starcounter-Jack/JSON-Patch/blob/master/src/json-patch-duplex.js#L549
The question is how PuppetJS uses it with versioning.

**Comment by warpech** [comment]
I assume this is not a problem anymore or it would surface again. Archiving.
