### ISSUE TITLE
Can't create non-morphable links in the same domain

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#70]
I could not find another issue about this, so I'm starting a new one. 

PuppetDOM click capturing makes it impossible to create regular links in the same domain. All links in the same host & port are treated by [isApplicationLink](https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet-dom.js#L110) as "morphable", which may not be correct some at all times.

I don't have any specific proposal for solution. Ideas?

**Comment by miyconst** [comment]
Some specific css class could be used for this.

**Comment by warpech** [comment]
CSS is for presentation, but a HTML attribute can be used indeed. 

Should page morphing be opt-in or opt-out? Either we choose, it should not be hard to use. I think opt-out morphing would be easier to use.

Can we make it automatic? Gateway knows all the registered URI handlers, so theoretically that list could be exposed to the client for automated morphing of known URIs only.

**Comment by tomalec** [comment]
+1 for opt-out

However automatic solution you proposed would be easier for opt-in.

I would say that since morphing is related to PuppetDOM, such configuration should not be part of core puppet protocol.

**Comment by miyconst** [comment]
`opt-out` means that this anchor won't be morphed, if so, then I vote for this as well.

Something like this?
```html
<a href="/full/reload/page" opt-out="true">Click me</a>
```


>Can we make it automatic? Gateway knows all the registered URI handlers, so theoretically that list could be exposed to the client for automated morphing of known URIs only.

Then we have to teach client side to recognize the Starcounter url patterns. Also this makes impossible to add a non-morphing anchor to any registered handler.

It might be needed in some cases.

**Comment by warpech** [comment]
Yes, by opt out I mean that link morphing should be on by default, unless you disable it by using an attribute.

This looks better:

```
<a href="/full/reload/page" external>Click me</a>
```

**Comment by miyconst** [comment]
Yes, looks good, but custom attributes are not valid in HTML5. It should be:

```html
<a href="/full/reload/page" data-external>Click me</a>
```
To pass w3c validator: https://validator.w3.org/nu/.

**Comment by warpech** [comment]
To keep it valid and semantic, we could use:

```html
<a href="/full/reload/page" rel="external">Click me</a>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types

**Comment by mtornwall** [comment]
+1 for a mechanism for opt-out.

**Comment by warpech** [comment]
Simple hack is to add one line before the end of PuppetDOM.isApplicationLink:

```js
PuppetDOM.isApplicationLink = function (elem) {
    if (typeof elem === 'string') {
      //type string is reported in Polymer / Canary (Web Platform features disabled)
      var parser = document.createElement('A');
      parser.href = elem;

      // @see http://stackoverflow.com/questions/736513/how-do-i-parse-a-url-into-hostname-and-path-in-javascript
      // IE doesn't populate all link properties when setting .href with a relative URL,
      // however .href will return an absolute URL which then can be used on itself
      // to populate these additional fields.
      if (parser.host == "") {
        parser.href = parser.href;
      }

      elem = parser;
    }
    if (elem.rel === "external") {
      return false;
    }
    return (elem.protocol == window.location.protocol && elem.host == window.location.host);
  };
```

**Comment by mtornwall** [comment]
@warpech's proposed doesn't appear to solve the problem. In my tests I always have `typeof elem === 'string'`, so it always proceeds to create a new node (sans the `rel` attribute).

**Comment by warpech** [comment]
Seems to be specific to Polymer... @tomalec can you take a look into that at some time in the future?

**Comment by warpech** [comment]
Polymer has a different pattern for a similar problem on https://elements.polymer-project.org/. They use an opt-in strategy:

```html
<a is="app-link" href="...">internal link</a>
```

src: https://github.com/Polymer/polymer-element-catalog/blob/master/app/elements/app-link/app-link.html

**Comment by warpech** [comment]
I was thinking more about the opt-in idea, and I think it follows the Web Components way much better. In our case, this could be:

```
<a is="puppet-link" href="...">internal link</a>
```

Of course, switching to an opt-in mechanism would hurt the existing apps, but it will degrade gracefully to a regular page reload.

@miyconst, @tomalec, @mtornwall, @malx122, @Starcounter-Jack, @jakubklekota does it make any difference for you?

**Comment by miyconst** [comment]
I think, it is a good idea, even though we will have to fix all of our apps.

Right now puppet catches links like a magic, and with `is="puppet-link"` it will be obvious for developers, that this link will be caught by puppet, and if they don't know what that is, they will go to docs/wiki and learn.

**Comment by mtornwall** [comment]
> Right now puppet catches links like a magic, and with is="puppet-link" it will be obvious for developers, that this link will be caught by puppet, and if they don't know what that is, they will go to docs/wiki and learn.

This.

**Comment by andwah** [comment]
*bump*

**Comment by warpech** [comment]
Recently I like to take inspiration from Turbolinks (see: https://github.com/StarcounterApps/KitchenSink/issues/144#issuecomment-311184846)

What they do is hijack all links in the same domain. To opt-out, use `data-turbolinks="false"` (see https://github.com/turbolinks/turbolinks#disabling-turbolinks-on-specific-links).

Our initial proposal was opt-out, too. Potential attributes:

- `data-palindrom="false"`
- `rel="external"` (https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types)

**Comment by alshakero** [comment]
+1 for `rel="external"`.

`data-palindrom` is long, locks 'palindrom' name, has a brand in it, and doesn't convey what it does.

`rel="external"` is perfect IMO.

**Comment by warpech** [comment]
@tomalec what's your feeling towards `rel="external"`? I know it is a standarised attribute, maybe its wrong to give it a special meaning in Palindrom?

**Comment by warpech** [comment]
Solution for this is to use `target="_top"` with Palindrom 3.0.2 or newer (added in https://github.com/Palindrom/Palindrom/pull/145).

@alshakero please document this solution.

**Comment by alshakero** [comment]
> @alshakero please document this solution.

PRed here https://github.com/Palindrom/Palindrom/pull/167

**Comment by alshakero** [comment]
Closing as done and documented [here](https://palindrom.github.io/#/docs/master/05-_Navigation_Interception).
