### ISSUE TITLE
[PuppetDOM] Do not morph pages for links with target="_blank"

### ISSUE THREAD

**Issue by tomalec** [Palindrom/Palindrom#73]
as they are supposed to open new tab/window

**Comment by warpech** [comment]
Actually I propose: don't morph pages with `target` different than undefined, empty or "self".

**Comment by miyconst** [comment]
+1. This has just hit me.

**Comment by warpech** [comment]
Just discussed: @tomalec will implement this

**Comment by alshakero** [comment]
Is this still an issue? I don't think it's implemented. Can I take it?

**Comment by tomalec** [comment]
Please do.

**Comment by alshakero** [comment]
What if someone has iframe and wants to use it as a target? What does Palindrom actually do currently in this case?

**Comment by warpech** [comment]
> What if someone has an iframe and wants to use it as a target? What does Palindrom actually do currently in this case?

Looking at the code, it hijacks that link anyway, ignoring the `target`.

**Comment by alshakero** [comment]
@warpech ah awesome

**Comment by warpech** [comment]
Reopening this issue for explaining the `target` behavior in the Docs.

**Comment by alshakero** [comment]
Closing as done and documented [here](https://palindrom.github.io/#/docs/master/05-_Navigation_Interception).
